---
- name: Provision EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Launch EC2 Instance
      ec2:
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        group: "{{ security_group }}"
        count: 1
        instance_tags:
          Name: nginx-ansible
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 300
        state: started
      with_items: "{{ ec2.instances }}"
