---
- name: Provision EC2 Instance and Deploy Nginx with Custom Page
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Provision EC2 instance
      ec2:
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
        group: "{{ security_group }}"
        count: 1
        instance_tags:
          Name: nginx-ansible
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Install Docker and Deploy Nginx
  hosts: launched
  become: yes
  vars:
    html_dir: /home/ubuntu/nginx-html

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create HTML directory
      file:
        path: "{{ html_dir }}"
        state: directory

    - name: Upload custom index.html
      copy:
        src: custom_index.html
        dest: "{{ html_dir }}/index.html"

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ html_dir }}:/usr/share/nginx/html:ro"
